version: "3"
services:
  web_blackandorange:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    ports:
      - "3015:3000"
    volumes: 
      - ./blackandorange:/opt/app
      - gem_cache_blackandorange:/gems
    env_file: 
      - .env/development/database_blackandorange
      - .env/development/web_blackandorange
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server_blackandorange
    networks:
      - network
  webpack_dev_server_blackandorange:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: ./bin/webpack-dev-server
    ports: 
      - "3050:3050"
    volumes: 
      - ./blackandorange:/opt/app
      - gem_cache_blackandorange:/gems
    env_file: 
      - .env/development/database_blackandorange
      - .env/development/web_blackandorange
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    networks:
      - network
  database_blackandorange:
    image: postgres
    env_file: 
      - .env/development/database_blackandorange
    volumes: 
      - db_data_blackandorange:/var/lib/postgresql/data
    networks:
      - network
volumes: 
  db_data_blackandorange:
  gem_cache_blackandorange:
networks:
  network: