version: "3"
services:
  web_blackandorange:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    ports:
      - "3003:3000"
    volumes: 
      - ./blackandorange:/opt/app
      - gem_cache_blackandorange:/gems
    env_file: 
      - .env/development/database_blackandorange
      - .env/development/web_blackandorange
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server_blackandorange
    networks:
      - network_blackandorange
  webpack_dev_server_blackandorange:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: ./bin/webpack-dev-server
    ports: 
      - "4003:4014"
    volumes: 
      - ./blackandorange:/opt/app
      - gem_cache_blackandorange:/gems
    env_file: 
      - .env/development/database_blackandorange
      - .env/development/web_blackandorange
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    networks:
      - network_blackandorange
  database_blackandorange:
    image: postgres:13
    env_file: 
      - .env/development/database_blackandorange
    volumes: 
      - db_data_blackandorange:/var/lib/postgresql/data
    networks:
      - network_blackandorange
volumes: 
  db_data_blackandorange:
  gem_cache_blackandorange:
networks:
  network_blackandorange:
    ipam:
      driver: default
      config:
        - subnet: "172.10.3.0/24"